[build]
  publish = "dist/static"
  command = "ng build --prod && npm run scully"
[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugin.config]
  baseUrl = "https://test-build-plugins.netlify.com/"
  buildDir = "dist/static"
